### ISSUE TITLE
game freeze at stage 7 (1.12.2)

### ISSUE THREAD

**Issue by KenyMylankca** [dragon-forge/HammerLib#1]
can u fix this?

**Comment by NyanMC** [comment]
without further information, such as a latest.log or at least confirmation that the issue occurs with just hammerlib installed by itself, then no, zeith will not be able to fix this

**Comment by KenyMylankca** [comment]
just install the hammerlib ALONE on forge 2855 and you will see that the game startup freezes at fl stage 7.
and this is what the logs say:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
