### ISSUE TITLE
Client freezes on startup in packs with Wolf Armor and Storage mod 1.12.2

### ISSUE THREAD

**Issue by tyon2006** [dragon-forge/HammerLib#17]
Hey! I've got a bit of a weird one. When I update Wolf Armor and storage to anything newer than v3.4.1.1, it prevents my client from launching (you click play and the client never opens or displays forge loading screen). A java thread is running on my computer, but letting it run or killing the thread does not produce a crash log.

So, why am I posting this here? LOL
When i ran a visualVM to see what was freezing, this came up: 
![image](https://user-images.githubusercontent.com/26413035/183301987-d7ec27c3-0093-4577-8841-9e747dc8263e.png)

This is the only thing that's actually running in the instance, so it seems like the 2 mods together are causing a weird interaction. Could you take a look at this?

**Comment by Zeitheron** [comment]
This is a separate thread, it does not really affect the main game thread in any way, especially while it's idling.

**Comment by tyon2006** [comment]
Good to know! If you're confident it's not you, then we can go ahead and close. Thanks for checking.

Still strange to me that it's the *only* thing actually visible to VisualVM. This may not be your problem, but any clues on how I could check what's causing the crash if there's no log, no crashlog, and VisualVM cannot see it?
