### ISSUE TITLE
HammerLib 1.19.2

### ISSUE THREAD

**Issue by rowdy116** [dragon-forge/HammerLib#20]
Version 19.1.34 worked for me however version 19.1.35 and up did not. I am using this Lib for Improvable-Skills-Mod-Forge-1.19.2.

**Comment by Zeitheron** [comment]
Never download mods from sites like 9minecraft. You got a misconfiguration of versions because of that.
Get the LATEST versions of both HammerLib AND IS3:
- https://www.curseforge.com/minecraft/mc-mods/hammer-lib/files/all
- https://www.curseforge.com/minecraft/mc-mods/improvable-skills/files/all
