### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by Toma400** [dragon-forge/HammerLib#29]
I had a crash when trying to create new world in 1.20.1 Minecraft (Forge 47.0.34). After updating HammerLib to 20.1.8 version, crash still happen.

[latest.log](https://github.com/dragon-forge/HammerLib/files/11916287/latest.log)

**Comment by Zeitheron** [comment]
This is ImprovableSkills crashing.

**Comment by Zeitheron** [comment]
Fixed.
