### ISSUE TITLE
[1.18] Crash before loading with Tinkers & Hammerlib

### ISSUE THREAD

**Issue by BonaireDreams** [dragon-forge/HammerLib#3]
MC 1.18.1
Forge 39.1.2
Tinkers Construct 3.4.2.60
Hammerlib 1.18.1-18.1.11 

Custom modpack Game crashes before loading with Hammerlib 1.18.1-18.1.11 & Tinkers 3.4.2.60
Same modpack configuration works fine with Tinkers 1.18.1-3.4.1.46
Not sure if Tinkers or Hammerlib issue. Opening on their Github as well.

[https://pastebin.com/122v1NTw](url)

**Comment by Zeitheron** [comment]
#2

**Comment by BonaireDreams** [comment]
Fixed by updating JEI to the last available BETA for 1.18.1 JEI-1.18.1-9.4.1.112. Odd that the pack ran fine for weeks and only crashed when I updated Tinkers to the newer version today. Seems others were getting a similar crash with other mods (Pnuematicraft etc) but it was JEI that needed to be updated to this latest Beta version.

**Comment by ghost** [comment]
> 

Im on JEI 1.18.1.-9.4.1.172 and still crashing?
