### ISSUE TITLE
Freezes during startup 1.12.2

### ISSUE THREAD

**Issue by Shevre** [dragon-forge/HammerLib#30]
The latest 2 versions of hammerlib for 1.12.2 (2.0.6.33 and 2.0.6.34, 2.0.6.32 doesn't have this issue) freeze during startup and i don't really know why because it just seems to stop and doesn't really give me any useful information in the log
[latest.log](https://github.com/dragon-forge/HammerLib/files/12373788/latest.log)

**Comment by Zeitheron** [comment]
There really is absolutely nothing in the logs.
Sorry, can't help.
