### ISSUE TITLE
Detecting wrong fml version

### ISSUE THREAD

**Issue by festro** [dragon-forge/HammerLib#32]
Hammerlib is not reading the correct version of the forge modloader, It claim it want's 47.1+ and that I have "47", I have 47.1.47
this causes hammerlib to not load which in turn registers as not installed with other mods requiring it ultimately resulting in the missing dependency error screen upon load.
[crash-2023-09-05_14.03.53-fml.txt](https://github.com/dragon-forge/HammerLib/files/12528345/crash-2023-09-05_14.03.53-fml.txt)

**Comment by Zeitheron** [comment]
Rollback to the version of HammerLib which did not cause this issue.

**Comment by festro** [comment]
Not to sound rude but that's a given, the whole point of reporting is to expose the issue so it gets fixed.

**Comment by Zeitheron** [comment]
I have moved onto Neoforge, and was building against it. Try the latest build, if it fixes your issues.

**Comment by festro** [comment]
Thank you, yes this fixed my issue.
________________________________
