### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by uhloin** [dragon-forge/HammerLib#34]
[crash-2023-09-20_20.10.38-client.txt](https://github.com/dragon-forge/HammerLib/files/12675337/crash-2023-09-20_20.10.38-client.txt)

HammerLib-1.20.1-20.1.20.jar

**Comment by Zeitheron** [comment]
Please update Rubidium to 0.7.0a and provide a new crash report.

**Comment by uhloin** [comment]
Rubidium 0.7+ is buggy and does not run  because incompatible with Oculus and shaders

**Comment by Zeitheron** [comment]
I am not able to support older versions of rubidium since it does not have an API that I can use to actually make it work.

**Comment by uhloin** [comment]
OK. I have no other idea than wait for fix in Rubidium or Oculus and do not update HammerLib from 20.1.19 for some time.
Could you instead of mysterious crash just write user-friendly error message on start like "HammerLib since 20.1.20 requires Rubidium 0.7+" ?

**Comment by Zeitheron** [comment]
I will do two things right now.
Add support for future Rubidium, as well as add a config option that disables the new feature when Rubidium is detected.
Currently going to debug things with both versions to make optimal changes.

**Comment by uhloin** [comment]
Just as update
Oculus is updated to new version oculus-mc1.20.1-1.6.9.jar and works fine together with HammerLib-1.20.1-20.1.22.jar and embeddium-0.1.9+mc1.20.1.jar (this "embeddium" probably is like rubidium 0.7+)

**Comment by Zeitheron** [comment]
Does the colored glint function properly ?

**Comment by Zeitheron** [comment]
Can confirm it works just fine on both 1.19.2 and 1.20.1 (custom glint)

I pushed it as a new build which re-enables the colored glint with embeddium, as well as added a warning message for rubidium users to migrate over to embeddium for better compatibility.
That, and a few other minor tweaks to code.

Thanks a lot for your investigation into this!
