### ISSUE TITLE
Server Crash 20.1.21

### ISSUE THREAD

**Issue by DinnerBeef** [dragon-forge/HammerLib#35]
https://s.dinnerbeef.com/gOXe5/MovUSeWo76.txt

Server crashing on newest update of mod

**Comment by Zeitheron** [comment]
Why do you have Rubidium on the server? 🤨

**Comment by DinnerBeef** [comment]
👁️ Because I missed that one

**Comment by Zeitheron** [comment]
Try without it, should boot up, hopefully!
