### ISSUE TITLE
Crash rendering Enchanted Golden Apple or Nether Star

### ISSUE THREAD

**Issue by ElRichiRicon** [dragon-forge/HammerLib#36]
Using version 19.3.71
Forge 43.2.23

https://pastebin.com/wUpqiUgj

Trying to open the Foodstuffs creative tab crashes the game. Also scrolling down a bit in the Miscelaneous tab.
Enchanted books render normally.

**Comment by Zeitheron** [comment]
Can you please provide debug/latest log, please? It would greatly help.

**Comment by Zeitheron** [comment]
Figured it out. Mixin wasn't applying for 1.19.2 but otherwise works fine in 1.20.1
Slightly changed the mixin point to address this issue.
