### ISSUE TITLE
[1.12.2] `McHooks.tickTile()` causing notable lag

### ISSUE THREAD

**Issue by Krutoy242** [dragon-forge/HammerLib#37]
I run Spark profiler `/spark profiler --timeout 100`

And got this resilt: https://spark.lucko.me/sfE4XTS6OS

I found, that `self time` of `com.zeitheron.hammercore.asm.McHooks.tickTile()` took too much. Its about 1% of my TPS.

![image](https://github.com/dragon-forge/HammerLib/assets/936618/e9257a90-af1f-44a6-aa4f-f131220cc934)

I found that [this code](https://github.com/dragon-forge/HammerLib/blob/1.12.2/src/main/java/com/zeitheron/hammercore/asm/McHooks.java#L30-L40) is handling some kind of tile entities halting. I'm not using `tile_entity_tick_slip` config at all, so i believe i don't need this feature at all.

[debug.log](https://github.com/dragon-forge/HammerLib/files/12707999/debug.log)

Is this 1% lag is normal? Can i somehow disable or fix this?

**Comment by Zeitheron** [comment]
Just disable the tick slip altogether. `asm/hammercore.xml` - you will need to change `World.ITickable.Override` from `true` to `false`.
