### ISSUE TITLE
[bug] Incompatibility with IronJetPacks

### ISSUE THREAD

**Issue by CKY-** [dragon-forge/HammerLib#38]
with iron jetpacks and hammerLib installed 
the iron jetpaks Items fail to load 

https://github.com/BlakeBr0/IronJetpacks/issues/78

SolarFluxReborn-1.19.2-19.3.10
HammerLib-1.19.2-19.3.73

**Comment by Zeitheron** [comment]
I would suggest isolating this issue into a separate modpack with IronJetpacks and HammerLib, and see what happens.
There is no useful information that can be used to fix this issue so far.
