### ISSUE TITLE
1.12.2 incompatibility with SpongeForge / temp solution inside

### ISSUE THREAD

**Issue by cajlo** [dragon-forge/HammerLib#39]
incompatibility with SpongeForge
tested HammerLib-1.12.2-2.0.6.37.jar (and previous) with : spongeforge-1.12.2-2838-7.4.8-RC4142.jar ; spongeforge-1.12.2-2838-7.4.7.jar

found temporarily solution - open jar and delete folder ASM (not sure it is a good thing)

**Comment by Zeitheron** [comment]
disable TickSlip in .minecraft/asm/hammercore.xml
