### ISSUE TITLE
Hammerlib Crashes with Flywheel 1.18-0.6.1

### ISSUE THREAD

**Issue by gamenTV** [dragon-forge/HammerLib#4]
The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot read field "internal" because the return value of "org.zeith.hammerlib.api.config.ConfigHolder.getCurrent()" is null
Exit-Code: - 1
[crash-2022-03-17_17.51.43-client.txt](https://github.com/dragon-forge/HammerLib/files/8289860/crash-2022-03-17_17.51.43-client.txt)

**Comment by Zeitheron** [comment]
#2
