### ISSUE TITLE
hammerlib causing create ore excavation to crash

### ISSUE THREAD

**Issue by Tsumiki129** [dragon-forge/HammerLib#44]
hi i have discovered that your mod is causing a conflict with the create ore excavation mod were the ore vain finder of the mod wont work in finding ores and the excavator crashes the game wen placed.

forge version 47.2.1 Minecraft version 1.20.1

**Comment by Zeitheron** [comment]
Provide crashes, logs and other relevant information.

**Comment by tom5454** [comment]
https://github.com/dragon-forge/HammerLib/blob/1.20.1/src/main/java/org/zeith/hammerlib/mixins/RecipeManagerMixin.java#L43
The id argument can be null with vanilla, but crashes with hammerlib installed.

Original issue: https://github.com/tom5454/Create-Ore-Excavation/issues/61
