### ISSUE TITLE
Crash on server boot

### ISSUE THREAD

**Issue by Gohu0** [dragon-forge/HammerLib#45]
Hello, HammerLib failed to load when I start a server with SolarFlux and GTCEU Modern.
Minecraft: 1.20.1
Forge: 47.1.43
HammerLib-1.20.1-20.1.23
SolarFluxReborn-1.20.1-20.1.3
gtceu-forge-1.20.1-1.0.14.a
``Mod File: /home/container/mods/HammerLib-1.20.1-20.1.23.jar
Failure message: HammerLib (hammerlib) has failed to load correctly
java.lang.reflect.InvocationTargetException: null
Mod Version: 20.1.23
Mod Issue URL: https://github.com/dragon-forge/HammerLib/issues
Exception message: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.lowdragmc.lowdraglib.client.model.custommodel.LDLMetadataSection``
https://pastebin.com/yQh3HwbD

**Comment by Zeitheron** [comment]
For some reason, LowDragLib is trying to inject itself somewhere and load `com.lowdragmc.lowdraglib.client.model.custommodel.LDLMetadataSection` on server side.
The only reference of anything from HammerLib is the mention of [this line](https://github.com/dragon-forge/HammerLib/blob/1.20.1/src/main/java/org/zeith/hammerlib/HammerLib.java#L69C3-L69C3), whic registers the proxy to event bus.

I would have to sadly mark this issue as wont-fix, unless more information would be gathered, somehow.
