### ISSUE TITLE
Server crash 1.20.1

### ISSUE THREAD

**Issue by SeagalKru** [dragon-forge/HammerLib#46]
Hello!
I'm not good at understanding log files, but upon a quick look I saw a reference to your mod (I could be wrong, please forgive me in advance).
When you log into the server, the world takes a very long time to load and eventually the server crashes.

Attached are the log files:
- crash log:
[crash-2024-01-21_17.20.06-server.txt](https://github.com/dragon-forge/HammerLib/files/14001633/crash-2024-01-21_17.20.06-server.txt)
- additional log files:
[latest.log](https://github.com/dragon-forge/HammerLib/files/14001635/latest.log)
[debug.log](https://github.com/dragon-forge/HammerLib/files/14001636/debug.log)

Thank you for attention!

**Comment by Zeitheron** [comment]
Unrelated to HammerLib.

**Comment by SeagalKru** [comment]
Please excuse me!
Could you tell me which mod is responsible for the crash so that I can contact its developer?
Thank you!

**Comment by Zeitheron** [comment]
There is no single mod responsible for it. Your server just hangs for over 60 seconds, causing crash.

**Comment by SeagalKru** [comment]
Oh!
This means there is not enough RAM. It's time to change the tariff for improving allocated resources!
Thank you, dear Friend!
