### ISSUE TITLE
[1.20.1] compatibility with Sodium(Embeddium)

### ISSUE THREAD

**Issue by FrozenGalaxy** [dragon-forge/HammerLib#48]
Is this issue on your end?: https://gist.github.com/FrozenGalaxy/e2e8e04f2cd259092e5156f2496b757f

**Comment by embeddedt** [comment]
No, it was an Embeddium bug fixed in 0.3.4.

**Comment by FrozenGalaxy** [comment]
> No, it was an Embeddium bug fixed in 0.3.4.

Ah, thanks for fixing it :)
