### ISSUE TITLE
1.12.2 Crash when entering Dimension whit Coloured Lux and Little tiles

### ISSUE THREAD

**Issue by IvorAmlug** [dragon-forge/HammerLib#49]
So i had this issue for a while but temporarly got arround it by using vanilla fix to keep playing after crashes. But sadly i just realised that this sometimes breaks other mods until i restart. 
When ever i enter a Dimension near any Little tiles block the game just crashes. Odly only if Colored Lights from Colored Lux are active during or direclty after entering a Portal. I also dont Land anywhere near my Supposed exit Portal for the most part i  just get spawned somewhere.
When using Vanilla fix for playing after crash its sometimes names Colored Lux, Hammercore and Little tiles as potentional causes even though most times naming "unkown" to be the cause.

Mods and Versions used to Reproduce:
Coloured Lux 1.12.2-12.6.33
CreativeCore 1.12.2 1.10.71
Hammerlib 1.12.2 12.2.48
Little Tiles 1.12.2 1.5.85
Forge 1.12.2 14.23.5.2860

Its pretty Odd especially considering that Blocks affectet by Colored Lux for example if u have HyperLights installed will Glow in correct color even if Used as Little Tiles Components. Yet the Game still crashes on Dimension switch regardless if any Coloured Lighting is involved in the Little Tiles block being near. Can be a Importer or one tiny bit of sand it dosnt seem to matter.

I decidet to post this here as this should be the last place of a mod related to the crash that i havent posted at yet.

Some Crash logs:
[crash-2024-02-17_23.10.42-client.txt](https://github.com/dragon-forge/HammerLib/files/14320353/crash-2024-02-17_23.10.42-client.tx
[crash-2024-02-17_22.41.02-client.txt](https://github.com/dragon-forge/HammerLib/files/14320354/crash-2024-02-17_22.41.02-client.txt)
t)

I dont know if this can be fixed at all at ur side , and in the End 1.12 is a dead version so for now i just restart after dimension hoping or just build my Portals miles away from my base.

**Comment by Zeitheron** [comment]
This is fully on their part, as the stack trace throws exception `at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.allTiles(TileEntityLittleTiles.java:787)`
