### ISSUE TITLE
Server Crashes with Datapacks [1.18.2]

### ISSUE THREAD

**Issue by lays24mc** [dragon-forge/HammerLib#5]
As soon as I install the mod Hammerlib and datapacks from Vanilla Tweaks, my server always crashes with this error message: [https://pastebin.com/Xv6P3nGn](https://pastebin.com/Xv6P3nGn)

No crash log is created. It also doesn't matter which datapack I use from VanillaTweaks. An example would be MulitplayerSleep

Forge - 1.18.2 40.0.32
HammerLib -1.18.2-18.2.13

**Comment by Zeitheron** [comment]
Commented out a deprecated method that caused the crash.
