### ISSUE TITLE
Mana and artifice conflict with hammer lib

### ISSUE THREAD

**Issue by Dan1ss1mo** [dragon-forge/HammerLib#50]
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice
then both hammer lib and mana and artifice are present, opening MnA cantrip gui crash the game
to reproduce:
1) read arcane codex to get mana pool
2) get any of manaweaving wand
3) press ctrl right click
4) crash
https://pastebin.com/n01bAfRJ
Tested multiple version for 1.20.1, seems to be the case for all of them

**Comment by wmcook32** [comment]
I am having the same issue. Spoke with Mithion (Author of Mana and Artifice). He claims that it is an issue within Hammerlib.

**Comment by Zeitheron** [comment]
How... exactly is it HammerLib's fault...?

Doesn't seem like their source code is public, so I can't really judge, but I see not a single line in stack trace that could point to HammerLib causing the crash.

I can see some mixins in the stack trace, but none of them are of HammerLib.

**Comment by wmcook32** [comment]
The crash only happens when HammerLib is installed. Remove it and no crash.
[crash-2024-03-23_17.01.09-client.txt](https://github.com/dragon-forge/HammerLib/files/14733967/crash-2024-03-23_17.01.09-client.txt)

**Comment by Zeitheron** [comment]
Yeah sure, but what is their explanation besides just blaming another mod?
Like what was their research process, what did they find out and how it could be fixed?
This crash still doesn't have any HammerLib in the stack except [MinecraftMixin](https://github.com/dragon-forge/HammerLib/blob/1.20.1/src/main/java/org/zeith/hammerlib/mixins/client/MinecraftMixin.java), which doesn't do anything invasive whatsoever.

**Comment by Zeitheron** [comment]
Again, I don't have their source code, so I can not really see what's going on either.

**Comment by wmcook32** [comment]
I might have uploaded the wrong crash log, so I did a pastebin.

[Pastebin](https://pastebin.com/RY0vt8dL)

**Comment by Zeitheron** [comment]
It's pretty much the same crash.

**Comment by wmcook32** [comment]
As mentioned in the Discord, This is the message Mithion sent:

Mithion — Today at 6:39 PM
It's happening trying to look up recipes.  If they're doing something to recipe searching in the name of optimization, then they'll break it.

**Comment by Zeitheron** [comment]
I do not think there's anything related to recipe searching going on there. They are literally missing `if(patterns != null)` check

**Comment by Zeitheron** [comment]
This is the only thing that is related to recipes - [RecipeManagerMixin](https://github.com/dragon-forge/HammerLib/blob/1.20.1/src/main/java/org/zeith/hammerlib/mixins/RecipeManagerMixin.java)
It does not really interfere or change the expected vanilla behavior.

**Comment by border999** [comment]
https://github.com/Mithion/Mana-And-Artifice/issues/746#event-12496256208

**Comment by Zeitheron** [comment]
This has been actually fixed for once.
I appreciate your patience! <3

**Comment by Dan1ss1mo** [comment]
Glad to here it, thanks for you're work!
