### ISSUE TITLE
Useless wrench/gear recipes breaks other mods (1.20)

### ISSUE THREAD

**Issue by uhloin** [dragon-forge/HammerLib#51]
Specifically, cannot create Crescent Hammer from Thermal Series because of wrench of HammerLib

**Comment by Zeitheron** [comment]
You can disable these recipes inside HammerLib's configs.

**Comment by uhloin** [comment]
Thank you. But it's a bit... not user friendly. I mean both broken things by default and that config too.

**Comment by Zeitheron** [comment]
This is the first time I heard anyone having any issues, sorry.
I did not think it would be a big issue, but thought of an ability to disable the recipes anyway, just in case.
I think that mod configs is generally where one would look if there's anything they want to tweak inside a mod... >.>"
