### ISSUE TITLE
Keeps crashing 1.19.2 

### ISSUE THREAD

**Issue by Sz4lka** [dragon-forge/HammerLib#53]
### Hello my friend !
I've been using hammerlib since six months from now. 
But today its just keep crashing.
Can you help me fix it ? 
[crash-2024-03-27_13.10.07-client.txt](https://github.com/dragon-forge/HammerLib/files/14773037/crash-2024-03-27_13.10.07-client.txt)
[latest.log](https://github.com/dragon-forge/HammerLib/files/14773047/latest.log)
Thanks in advance !

**Comment by Zeitheron** [comment]
It's not HammerLib. see #52

**Comment by Sz4lka** [comment]
Thanks
and thank you for your quick reply !
