### ISSUE TITLE
1.12.2 stuck at startup - Constructing Mods 1/7 - Construction HammerLib

### ISSUE THREAD

**Issue by Tree4Free** [dragon-forge/HammerLib#55]
In a blank 1.12.2 instance with only Forge & HammerLib the instance hangs at startup.

I am on Windows 10 and used Prism Launcher 8.3 if that makes a difference.

![image](https://github.com/dragon-forge/HammerLib/assets/9843834/8bb078c5-8853-4819-8600-81c8bc261deb)

I cloned the source code and started a debugger to investigate this and it seems like the cause of the issue is the `com.zeitheron.hammercore.utils.java.io.win32.ZoneIdentifier#readADS` method.

In there the mod hangs at the `process.waitFor();` line:

```java
Process process = Runtime.getRuntime().exec(new String[] {
    "cmd.exe",
    "/c",
    "more",
    "<",
    toParse.toFile() + ":" + ads
});			

process.waitFor(); // <-- Here
```

I was able to start the minecraft instance after changing the code in `com.zeitheron.hammercore.utils.CommonMessages#printMessageOnIllegalRedistribution`
from

```
ModSourceAdapter.ModSource illegalSourceNotice = ModSourceAdapter.getModSource(modClass)
    .filter(ModSourceAdapter.ModSource::wasDownloadedIllegally)
    .orElse(null);
```

to

```
ModSourceAdapter.ModSource illegalSourceNotice = null;
```

**Comment by ZekIzLoupriora** [comment]
@Tree4Free I'm sorry to bother you a year after you posted that, but can you **please** tell me how did you do that? The issue is still unresolved, and I can't figure out how to do that myself.

**Comment by Tree4Free** [comment]
@ZekIzLoupriora Not sure how familiar you are with programming so I will try to explain it as simple as possible.

Disclaimer: _I have not fully tested those steps because the last time I interacted with this mod was around a year ago and I didn't want to spin up a minecraft instance right now to fully test this._

First make sure to switch the branch to the 1.12.2 version in that left dropdown and then on that green code dropdown on the right select Download ZIP.
![Image](https://github.com/user-attachments/assets/747e5d2d-2205-41c1-8f8d-873cd78c236d)

Then extract that zip file and open the file `src/main/java/com/zeitheron/hammercore/utils/CommonMessages.java` using a text editor like notepad++, vscode, windows notepad etc.

In that file search for that code block near the top of the file (approximately around line 17)

```java
ModSourceAdapter.ModSource illegalSourceNotice = ModSourceAdapter.getModSource(modClass)
    .filter(ModSourceAdapter.ModSource::wasDownloadedIllegally)
    .orElse(null);
```

and replace those three lines with this single line:

```java
ModSourceAdapter.ModSource illegalSourceNotice = null;
```

After saving that file go back to the root folder of the extracted zip and double click the `→ Build Locally.bat` file. It will probably open a command line instance and start compiling the mod. On my pc this took around 6 minutes but it might take longer depending on your CPU.

At the end you might either see something like

```
BUILD SUCCESSFUL

Total time: 5 mins 7.963 secs
```

or the command line window closes automatically, not sure right now. Either way after the build is done it should have created a folder `build` and you should have the jar file to install in the `build/libs` folder.

You will probably have 3 jars in there one sources jar, one deobf jar and one without any suffix, named something like `HammerLib-1.12.2-12.2.58.jar`. This is the one you want to use to install in your minecraft instance.

A quick warning **do not distribute that jar to others** as the mod has no license specified as far as I am aware meaning you are legally not allowed to share it without permission of the mod owner.

**Comment by ZekIzLoupriora** [comment]
@Tree4Free Thank you very much! I have tried it myself and couldn't compile it with Gradle - I guess Java just sucks (or that's because I have like 10 different versions of Java installed on my system, idk). I ended up using Recaf to patch the mod .jar directly and removing the META-INF folder from there since the game would not launch with it.

**Comment by Tree4Free** [comment]
@ZekIzLoupriora ah I tried compiling with java 8 meaning my JAVA_HOME environment variable pointed to the java 8 installation while compiling. Haven't heard of Recaf before but from a quick glance that looks way more complicated than setting the correct java version 😂 

Anyway if it works for you now I am glad that you were able to get it running this way. In case you encounter any issues because of the missing meta-inf folder I would advise trying the recompilation aproach again.

**Comment by Zeitheron** [comment]
This is a government issue on for Zek. RKN blocks cloudflare-based websites, and there is nothing I can do, asides from suggesting use of VPN.
