### ISSUE TITLE
"HammerLib was tampered by someone"

### ISSUE THREAD

**Issue by aAndrew3030** [dragon-forge/HammerLib#56]
Version 1.21-21.0.8 (neoforge) downloaded with the curseforge app shows this warning. Is this intended or a error?

**Comment by aAndrew3030** [comment]
<img width="515" alt="Screenshot 2024-06-18 082742" src="https://github.com/dragon-forge/HammerLib/assets/84727133/cc689ab1-734e-49c6-88de-7ed64afd6b9a">

**Comment by Zeitheron** [comment]
Fixed in 21.0.9!
