### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.zeith.hammerlib.HammerLib

### ISSUE THREAD

**Issue by nerofur** [dragon-forge/HammerLib#59]
[crash-2024-07-02_08.47.24-client.txt](https://github.com/user-attachments/files/16071219/crash-2024-07-02_08.47.24-client.txt)

**Comment by nerofur** [comment]
[latest.log](https://github.com/user-attachments/files/16072998/latest.log)

**Comment by Zeitheron** [comment]
Unrelated to HammerLib.

Judging by your logs, this is the actual error:
```
[10:55:45] [modloading-worker-0/WARN]: @Redirect conflict. Skipping globaldataandresourcepacks.mixins.json:PackConfigurationMixin->@Redirect::packConfiguration(Ljava/util/Set;Ljava/lang/Object;)Z with priority 1000, already redirected by create_new_age.mixins.json:MinecraftServerMixin->@Redirect::add(Ljava/util/Set;Ljava/lang/Object;)Z with priority 1000
```

Which is a conflict between `globaldataandresourcepacks` and `create_new_age`

**Comment by nerofur** [comment]
I see. any suggestions to fix this? I'm not entirely sure I understand. aside from it being related to create new age. the pack worked fine until i published it and tried to launch it

**Comment by Zeitheron** [comment]
You might want to try removing one of those mods and see what happens

**Comment by nerofur** [comment]
okay I re-read your post listing the actual error and im wondering.. could i adjust the priority of one to 999 so they dont conflict? and where would I do that to in the files for create new age? I'm sorry this isn't related to hammerlib so feel free to say no

**Comment by Zeitheron** [comment]
The priority is set by the mod developer inside the mixin class. This won't resolve the issue, however. That is because they are both redirects, pointing into the same spot, which is not allowed by mixin subsystem, regardless of their priority.
