### ISSUE TITLE
Client Crash with HammerLib and Applied Mekanistics

### ISSUE THREAD

**Issue by lays24mc** [dragon-forge/HammerLib#6]
The client crashes when you add the Applied Mekanistics mod. Since here is only the mod HammerLib in the Crahslog to read, I assume an error here. Crashlog: [https://pastebin.com/JLDBAyJe](url)

Forge 1.18.2-40.0.36
HammerLib 1.18.2-18.2.14
Applied Mekanistics 1.1.0-beta

**Comment by Cazadorsniper** [comment]
I got that crash as well but I don't have Applied Mekanistics.

**Comment by Norway174** [comment]
Got the same crash here. Wonder if it not Forge, but for Fabric? Because I'm using Forge 40.0.40.
