### ISSUE TITLE
[Neo 1.21] 21.0.12 : Can't startup with CC:Tweaked and Hammerlib

### ISSUE THREAD

**Issue by Switch-Back18** [dragon-forge/HammerLib#62]
https://gist.github.com/Zeitheron/a177f55b14245f2b3a7a1a4360508687

**Comment by Switch-Back18** [comment]
Work without CC:Tweaked, possibly Hammerlib and CC:Tweaked compatibility issue

**Comment by Zeitheron** [comment]
Fixed in 21.0.13
