### ISSUE TITLE
Weird freeze during mod construction (1.12.2)

### ISSUE THREAD

**Issue by UndertaleFan6** [dragon-forge/HammerLib#65]
I have an issue where HammerLib freezes on mod construction
![obraz](https://github.com/user-attachments/assets/65ad41ba-9535-4db4-9392-cc3b1e53d5dd)
I tried without every mod that uses HammerLib and it still freezes so the issue is most likely on HammerLib, but the modpack I'm using works on different computers other than mine

**Comment by Zeitheron** [comment]
#54
