### ISSUE TITLE
issue on neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [dragon-forge/HammerLib#69]
https://mclo.gs/Cc3bz6b
![image](https://github.com/user-attachments/assets/44dc1454-7a2b-43c2-b491-31147f8b70c3)

**Comment by Zeitheron** [comment]
Completely unrelated.

**Comment by VaporeonScripts** [comment]
how would it be unrelated? it says hammerlib(?)

**Comment by Zeitheron** [comment]
It doesn't.

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/a20feaca-ce23-4440-9c0d-b1d964417f18)

**Comment by Zeitheron** [comment]
That is a listener list, which is completely unrelated and any mod may listen for an event. The issue is inside a stack trace below.

**Comment by Zeitheron** [comment]
You already reported it to YIGD developer [#182](https://github.com/B1n-ry/Youre-in-grave-danger/issues/182) and they confirmed they will be fixing it, as it is in fact a problem on their end.

**Comment by Zeitheron** [comment]
![image](https://github.com/user-attachments/assets/eb3f105d-70cd-4895-ad54-f70820d2c4a2)
Furthermore, you can see the index of a listener that is causing the problem! Hope that helps.
